language: ruby
branches:
  only:
  - master
rvm:
- 2.2.3
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
exclude:
- vendor
sudo: false
env:
  global:
    secure: JuEogN8V19N4U0HqfzrN4m+H5rCG05gNNB10nwKYcyWHvkTCOOyKJ7DI/zr6ZzOdaKQzaWbwMGCYGGjb1EZ1DHLj/gz7U4kWrg2C7MsxwKNvDj4DjdqZ2mtIoxLExhtXJQcb+YpW2mqt+83H9fhKNJ0l7F1h+CuLSxFdPYVZBLT1CsMK+d2nB5ueI+UvMHyDaFIpF9KRILFPIgOHhWLJnTIuoSpk8///lym+kiw1bbb/wl1QHfeN4tuTwuQE62oobKMG0s63Q+8Y75SvARqUsZMq1fd1pTYl+gRNAikrful9dwO4ahQjqjBA0608xr6WGi3DINEK4kZvrGsSIcgDB0tBzFPDcCu7q+MgDffBf3P3kJwe2ewHe+gGfmZfODUm0YD2VgVt62yXevoMj4y1i19iaUzR2i6mHyMK20RktzMh4AHRD6AfeRIvVvviozhxDGXUNhzObkD3fFFumcIy+uvKq/tou6kcgekhFQ+BAotP9bKgQE4farnlExZoOMQI4mQyAjabGsp5ono1cb3Gp6L4GFFiwoL6Khz/EbYzJPedfQwdiA4FSoXEzbgu1yvXK5S0eHgs+aDIRTl7ig/T7CVtTtgaYnckqrUgGYviGfx/yll9Hn4QcqBCQu3qkdspLjVP90fkpWPnRj1u3U1N/yFdp9qPHTuVUn2erT+gPuA=
